default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
development:
  <<: *default
  database: pcosim_dev
test:
  <<: *default
  database: pcosim_tst
production:
  <<: *default
  database: pcosim_prd